### ISSUE TITLE
Retry failed tests in this project

### ISSUE THREAD

**Issue by heerqa** [serenity-bdd/serenity-exercises#1]
Hi John,

I am using serenity cucumber and running around 100 tests in a build.
Some of the test failed randomly due to timeout, but when i re rerun them they passed.
I have gone thru http://thucydides.info/docs/serenity-staging/#_retrying_failed_tests section and added
max.retries=4
junit.retry.tests=true 

in serenity.properties file and then I am running mvn clean verify serenity:aggregate -Dwebdriver.driver=firefox 
But the suite execute only once, it does not rerun the failed tests.
Is there i other setting I am missing?
Many thanks in advance!

Thanks
Shagufta

**Comment by wakaleo** [comment]
Hi Shagufta,

We have removed this feature from Serenity as it is already provided in the Maven surefire plugins (we need to update the documentation, though). As a rule, rerunning the tests is not an optimal solution to a timeout problem - it is much better if you can analyse the test and use waits for specific conditions or states where you can, as it will make the tests more trustworthy (and faster).

**Comment by heerqa** [comment]
Thanks for quick reply!
I will use the waits.
Closing this issue.

**Comment by spillai98** [comment]
This ticket is closed. I still have a doubt from this.
-- I'm using 'Serenity-cucumber' and not 'Serenity -junit'. 
--  I'm running my tests using "mvn -Dsurefire.rerunFailingTestsCount=2 clean verify" command and its not retrying the failed cases.

Can you guys please confirm if I'm doing it correctly.( I suspect this only works with 'Serenity-Junit' and not with 'Serenity-Cucumber', is that the case? ,

if yes, can you guys please suggest an approach to implement the retrying logic with 'Serenity-cucumber'. 

@wakaleo @heerqa ^^

**Comment by wakaleo** [comment]
The retry logic is part of the Maven Surefire and Failsafe plugins, not part of Serenity, and indeed these plugins run JUnit, not Cucumber. Since the scenario execution is run by Cucumber-JVM, not by the Serenity code, it would be tricky to manage this directly through Serenity.

**Comment by spillai98** [comment]
Thanks @wakaleo

**Comment by nbarrett** [comment]
Would be good to remove [this section](http://www.thucydides.info/docs/serenity/#_retrying_failed_tests) from the reference manual to avoid others (like me) spending time trying to get it to work! (also net.thucydides.core.ThucydidesSystemProperty#JUNIT_RETRY_TESTS should probably be removed or deprecated to minimise confusion)

**Comment by rakeshnambiar** [comment]
@wakaleo .. I hope still serenity won't support the re-run feature. Pls confirm

**Comment by Nikunj1703** [comment]
Is there any suggested work-around to re-run failing scenarios in serenity cucumber?

**Comment by handresc1127** [comment]
I runned the failure tests with Maven Surefire and i had several problems:
1st run: 346 Scenarios (91 failed, 255 passed)
3447 Steps (91 failed, 156 skipped, 3200 passed)
149m15.351s
rerun failure tests:
91 Scenarios (84 failed, 7 passed)
1103 Steps (84 failed, 140 skipped, 879 passed)
67m4.064s

- The serenity report has resume of all tests but the scenaries outline that had passed on the firts execution were pending finally.
- The sumary of tests sended by other plugin (slack) was only the retest. 91 Scenarios (84 failed, 7 passed)
- The sumary of tests on surefire output file was all test mergered. Tests run: 437, Failures: 67, Errors: 108


			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.0.0-M1</version>
				<configuration>
					<testFailureIgnore>true</testFailureIgnore>
					<includes>
						<include>**/RunnerTags.java</include>
					</includes>
					<rerunFailingTestsCount>1</rerunFailingTestsCount>
				</configuration>
			</plugin>

**Comment by rakeshnambiar** [comment]
@nbarrett @handresc1127 @Nikunj1703 @heerqa Re-try feature didn't even works for me. I am using the below mentioned work-around for my JUnit Tests.

- Using the @After hook capture the Test case tag name (@TC01_RegressionTest) in case the test is failed
- Write all the failed Test case tags to a text file in the 'target' folder
- Write a Re-run class to pick each test and run dynamically using 'jUnitCore.run' [call from Jenkins as a 
   Post-build step]
- To re-generate the combined report in Jenkins running the batch command
  'mvn -P domain-test net.serenity-bdd.maven.plugins:serenity-maven-plugin:2.0.11:aggregate'

Not sure any other easy work-around is available. Let me know in case you found a better option.

**Comment by william0096** [comment]
I'm actually using the following command with maven "mvn verify  -Dfailsafe.rerunFailingTestsCount=2", and it works properly, but I still have the issue with gradle, did someone solve it?
